### ISSUE TITLE
Cannot read property '$$' of undefined and Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by eden-lane** [rob-balfre/svelte-select#292] opened 2021-08-06 12:26 UTC
I've created a codesandbox with code from Usage section of README.md, but it doesn't work:

https://codesandbox.io/s/dazzling-snow-29p1x?file=/App.svelte

**Comment by rob-balfre** [comment] 2021-08-10 03:27
@eden-lane  no idea I'm afraid, not sure what codesandbox is doing to generate that error.  Can you reproduce the issue locally?

**Comment by eden-lane** [comment] 2021-08-10 05:53
@rob-balfre I had this issue locally few times and updating svelte to the last version helped. But I have no idea why is this happening in codesandbox :(

**Comment by rob-balfre** [comment] 2021-08-15 22:59
@eden-lane ahh yes, it's probably because the build bundle is using a different version of svelte then. It's best practice to compile all .svelte files per project but svelte-select includes a pre-built bundle incase that's not an option. This is probably being used by codesandbox and causing the error.  I'm going to be migrating this project to sveltekit and use their 
built it packaging method (https://kit.svelte.dev/docs#packaging). Just waiting until kit hits v1.  Hopefully the official way to package will fix these issues going forward. 

In the meantime force codesandbox to use the .svelte file:
`import Select from "svelte-select/src/Select.svelte";`

**Comment by rob-balfre** [comment] 2022-04-12 00:52
Fixed in v5

**Closed by rob-balfre** 2022-04-12 00:52 UTC
