### ISSUE TITLE
Clear `selectedValue` on `select` event

### ISSUE THREAD

**Issue by jackwestmoretab** [rob-balfre/svelte-select#211] opened 2020-12-10 13:59 UTC
I can't figure out a way of doing this on my own, and would appreciate some help! 🙏 

Is there a way of clearing the select input field when the `select` event is fired? I.e. I select an item from the list, and the input is then cleared again (rather than the default, which is to display the selected item's label in the field).

Please let me know if that's clearly explained!

**Comment by rob-balfre** [comment] 2020-12-10 21:28
Duplicate of https://github.com/rob-balfre/svelte-select/issues/97

REPL https://svelte.dev/repl/f8198af9d51e4aecaf0832332a01614e?version=3.12.1

**Closed by rob-balfre** 2020-12-10 21:28 UTC
