### ISSUE TITLE
svelte-select does not render well with sapper and bulma.  

### ISSUE THREAD

**Issue by instantwpuserwin** [rob-balfre/svelte-select#112] opened 2020-03-01 05:48 UTC
svelte-select works very well in a sapper start template.  Looks great as well.
Sample code given here works well. 

But when I bring bulma in, svelte-select does not render well for some reason.
Once I make a selection from the  select control, I can see 2 big X's, way down the screen.

I am positive this is a config issue at my side. I checked issues here and no one has raised this issue.  

I am attaching my rollup.config.js as well as package.json file.

Please take a look. 

Thanks a lot.
[package.zip](https://github.com/rob-balfre/svelte-select/files/4271407/package.zip)

**Comment by rob-balfre** [comment] 2020-03-01 06:11
@instantwpuserwin Bulma CSS seems to work OK in the REPL...
https://svelte.dev/repl/7703dbd37e4a40b7996cf920e1ac7822?version=3.19.1

I don't want to get in the habit of downloading .zip files so you're going to have to create a repo or paste the code in there I'm afraid.

**Comment by instantwpuserwin** [comment] 2020-03-01 06:33
Thanks  for looking into this. 

=================================
Package.json file:
{
  "name": "TODO",
  "description": "TODO",
  "version": "0.0.1",
  "scripts": {
    "dev": "sapper dev",
    "build": "sapper build --legacy",
    "export": "sapper export --legacy",
    "start": "node __sapper__/build",
    "cy:run": "cypress run",
    "cy:open": "cypress open",
    "test": "run-p --race dev cy:run"
  },
  "dependencies": {
    "apollo-boost": "^0.4.4",
    "body-parser": "^1.19.0",
    "bulma": "^0.8.0",
    "compression": "^1.7.1",
    "connect-redis": "^4.0.3",
    "express-session": "^1.17.0",
    "graphql": "^14.5.8",
    "node-fetch": "^2.6.0",
    "polka": "^1.0.0-next.9",
    "redis": "^2.8.0",
    "sirv": "^0.4.2",
    "sirv-cli": "^0.4.4",
    "svelte-apollo": "^0.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/runtime": "^7.0.0",
    "@rollup/plugin-commonjs": "^11.0.0",
    "@rollup/plugin-node-resolve": "^6.0.0",
    "@rollup/plugin-replace": "^2.2.0",
    "node-sass": "^4.13.1",
    "npm-run-all": "^4.1.5",
    "rollup": "^1.20.0",
    "rollup-plugin-babel": "^4.0.2",
    "rollup-plugin-postcss": "^2.0.3",
    "rollup-plugin-svelte": "^5.0.1",
    "rollup-plugin-terser": "^5.2.0",
    "sapper": "^0.27.0",
    "svelte": "^3.0.0",
    "svelte-select": "^3.4.0"
  }
}
=================================
rollup.config.js:

import resolve from '@rollup/plugin-node-resolve';
import replace from '@rollup/plugin-replace';
import commonjs from '@rollup/plugin-commonjs';
import svelte from 'rollup-plugin-svelte';
import babel from 'rollup-plugin-babel';
import postcss from 'rollup-plugin-postcss'
import { terser } from 'rollup-plugin-terser';
import config from 'sapper/config/rollup.js';
import pkg from './package.json';

const mode = process.env.NODE_ENV;
const dev = mode === 'development';
const legacy = !!process.env.SAPPER_LEGACY_BUILD;

const onwarn = (warning, onwarn) => (warning.code === 'CIRCULAR_DEPENDENCY' && /[/\\]@sapper[/\\]/.test(warning.message)) || onwarn(warning);
const dedupe = importee => importee === 'svelte' || importee.startsWith('svelte/');

export default {
	client: {
		input: config.client.input(),
		output: config.client.output(),
		plugins: [
			replace({
				'process.browser': true,
				'process.env.NODE_ENV': JSON.stringify(mode)
			}),
			svelte({
				dev,
				hydratable: true,
				emitCss: true
			}),
			resolve({
				browser: true,
				dedupe
			}),
			commonjs(),

			legacy && babel({
				extensions: ['.js', '.mjs', '.html', '.svelte'],
				runtimeHelpers: true,
				exclude: ['node_modules/@babel/**'],
				presets: [
					['@babel/preset-env', {
						targets: '> 0.25%, not dead'
					}]
				],
				plugins: [
					'@babel/plugin-syntax-dynamic-import',
					['@babel/plugin-transform-runtime', {
						useESModules: true
					}]
				]
			}),

			!dev && terser({
				module: true
			}),
			postcss()
		],

		onwarn,
	},

	server: {
		input: config.server.input(),
		output: config.server.output(),
		plugins: [
			replace({
				'process.browser': false,
				'process.env.NODE_ENV': JSON.stringify(mode)
			}),
			svelte({
				generate: 'ssr',
				dev
			}),
			resolve({
				dedupe
			}),
			commonjs()
		],
		external: Object.keys(pkg.dependencies).concat(
			require('module').builtinModules || Object.keys(process.binding('natives'))
		),

		onwarn,
	},

	serviceworker: {
		input: config.serviceworker.input(),
		output: config.serviceworker.output(),
		plugins: [
			resolve(),
			replace({
				'process.browser': true,
				'process.env.NODE_ENV': JSON.stringify(mode)
			}),
			commonjs(),
			!dev && terser()
		],

		onwarn,
	}
};
=====================================

**Comment by rob-balfre** [comment] 2020-03-01 06:42
@instantwpuserwin do you have bulma/sass working without svelte-select?

**Comment by instantwpuserwin** [comment] 2020-03-01 06:49
Hey,

"do you have bulma/sass working without svelte-select?"
Yes. It works well. 

I am attaching screenshots of before and after selections.
Please take a look. 

![Select screen before](https://user-images.githubusercontent.com/39667354/75621116-a34b0680-5bb6-11ea-862b-375ea50ae726.png)

![Select screen after selection](https://user-images.githubusercontent.com/39667354/75621114-a1814300-5bb6-11ea-86cd-3d477a7ad5c9.png)

**Comment by rob-balfre** [comment] 2020-03-01 06:55
@instantwpuserwin what's your postcss setup?

**Comment by instantwpuserwin** [comment] 2020-03-01 07:12
-------------------
rollup-config.js
I do import it :
import postcss from 'rollup-plugin-postcss'

and then call postcss() under client:  

Please see above for details.
-----------
In package.json, I have "rollup-plugin-postcss" under devDependencies
"rollup-plugin-postcss": "^2.0.3",
----------------------

Is this helping? 


-----------------------

**Comment by tomaszijdemans** [comment] 2020-03-23 10:54
I get the same behavior when using Tailwindcss. See: http://pg-air.surge.sh/

**Comment by rob-balfre** [comment] 2020-03-23 20:17
hmmm do you have a repo you can share so I can take a proper look at your build setup? For whatever reason your build is not exporting any CSS from svelte-select.

**Comment by rob-balfre** [comment] 2020-03-24 20:34
@tomzij thanks for sharing your repo.  It works fine for me after running `yarn` then `yarn dev` on MacOS Catalina + Node v13.5.0.

**Comment by tomzij** [comment] 2020-03-24 21:25
Thanks so much for looking into it!

Yeah, it seems to work locally, but then if I push it to surge I get the css errors as described in github. Very odd!

Thanks again for looking into it! I'll try running the code in Azure to see if that makes any difference

On Mar 24, 2020 21:34, Rob B <notifications@github.com> wrote:

@tomzij<https://github.com/tomzij> thanks for sharing your repo. It works fine for me after running yarn then yarn dev on MacOS Catalina + Node v13.5.0.

-

**Comment by rob-balfre** [comment] 2020-03-24 22:50
Might be this in your postcss.config.js 

```
  module.exports = {
    plugins: [
      require('tailwindcss'),
      ...(production ? [purgecss] : [])
    ]
  };
  ```

Maybe purgecss isn't compatible with svelte?

**Comment by tommyk** [comment] 2020-04-08 04:01
i am having the same issue, its something with purgecss.  so far, for the life of me, i have not found anything.  i can see the `selectContainer` in the bundle.css.map file, but it's gone if purgecss runs.  if i run locally (which kicks production to false, which stops purgecss from running) it will work.

i am so new to svelte and rollup i really can't tell you if the issue is somehow in this project or purgecss...

**Comment by aryaprakasa** [comment] 2020-06-04 08:06
Have you try to whitelist the css classes from purgecss?

```JS
const purgecss = require("@fullhuman/postcss-purgecss")({
  content: ["./src/**/*.svelte", "./public/**/*.html"],
  whitelist: ["selectContainer"],
  defaultExtractor: content => content.match(/[A-Za-z0-9-_:/]+/g) || []
});
```

**Comment by rob-balfre** [comment] 2020-06-26 00:38
Can I close this? Is it a svelte-select or build setup issue?

**Closed** 2020-08-13 22:04 UTC

**Comment by vedmant** [comment] 2020-11-02 10:24
Anyone who also have this problem, this is purgecss issue, you need to add this package to purgecss config:

		! dev && postcssPurgecss({
			content: ['./src/**/*.svelte', './src/**/*.html', './node_modules/svelte-select/**/*.svelte'],
			defaultExtractor: (content) => [...content.matchAll(/(?:class:)*([\w\d-/:%.]+)/gm)].map(([_match, group, ..._rest]) => group),
		}),
