### ISSUE TITLE
Can't add z-index to dropdown only

### ISSUE THREAD

**Issue by kihot** [rob-balfre/svelte-select#229] opened 2021-01-21 17:05 UTC
Is it possible to add z-index to dropdown only? I added z-index to component parent, but it's not working with two Select.
[screen "z-index in component parent"](https://prnt.sc/xdsl8y)

I need this because the dropdown is overlapping another element with z-index > 2

**Comment by evan-sheehan** [comment] 2021-01-21 17:56
It's a very inelegant solution, but I do this by watching to see when the dropdown opens. I then run a function that finds the dropdown in the DOM and changes the zIndex with JS.

For example: 
`$: if (listOpen) {
    changeZIndex();
  }
`

Where listOpen is a binding to the Svelte Select listOpen prop, and changeZIndex() searches the DOM and changes the zIndex style property. Would love a better solution if anyone has one.

**Comment by rob-balfre** [comment] 2021-01-27 21:14
Yeah, it's not ideal at the moment. It's on the list of things to improve in future updates. Just not soon unless it's via a PR.

Dupe of https://github.com/rob-balfre/svelte-select/issues/191

**Closed by rob-balfre** 2021-01-27 21:14 UTC
